sudo: required
language: python
jdk: openjdk8
services: docker
python: '3.6'
cache: pip
matrix:
  fast_finish: true
  include:
  - name: "Minimum Nextflow version, regular test suite"
    env: NXF_VER='0.32.0' SUITE=test FLAGS=
    language: java
    jdk: openjdk8
  - name: "Latest Nextflow version, regular test suite"
    env: NXF_VER='' SUITE=test FLAGS=
  - name: "Latest Nextflow version, default contrasts"
    env: NXF_VER='' SUITE=test FLAGS='--contrasts DEFAULT'
  - name: "Latest Nextflow version, no fastqc"
    env: NXF_VER='' SUITE=test FLAGS='--fastqc NO_FILE'
  - name: "Latest Nextflow version, no gene_list"
    env: NXF_VER='' SUITE=test FLAGS='--genelist NO_FILE'
  - name: "Lint the pipeline code"
    install:
      #Install nf-core/tools
      - pip install --upgrade pip
      - pip install nf-core
    script: nf-core lint ${TRAVIS_BUILD_DIR}
    python: '3.6'
    env: NXF_VER='0.32.0'
    jdk: openjdk8
  - name: "Lint the pipeline documentation"
    script: markdownlint ${TRAVIS_BUILD_DIR} -c ${TRAVIS_BUILD_DIR}/.github/markdownlint.yml
    python: '3.6'

before_install:
  # PRs to master are only ok if coming from dev branch
  - '[ $TRAVIS_PULL_REQUEST = "false" ] || [ $TRAVIS_BRANCH != "master" ] || ([ $TRAVIS_PULL_REQUEST_SLUG = $TRAVIS_REPO_SLUG ] && [ $TRAVIS_PULL_REQUEST_BRANCH = "dev" ])'
  # Pull the docker image first so the test doesn't wait for this
  - docker pull qbicsoftware/rnadeseq:dev
  # Fake the tag locally so that the pipeline runs properly
  # Looks weird when this is :dev to :dev, but makes sense when testing code for a release (:dev to :1.0.1)
  - docker tag qbicsoftware/rnadeseq:dev qbicsoftware/rnadeseq:dev

install:
  # Install Nextflow
  - mkdir /tmp/nextflow && cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  # Reset
  - mkdir ${TRAVIS_BUILD_DIR}/tests && cd ${TRAVIS_BUILD_DIR}/tests
  # Install markdownlint-cli
  - sudo apt-get install npm && npm install -g markdownlint-cli

script:
  - travis_wait 30 nextflow run ${TRAVIS_BUILD_DIR} -profile ${SUITE},docker ${FLAGS}
