# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
# use this to find packages: https://anaconda.org/
name: qbic-pipelines-rnadeseq-2.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::bioconductor-deseq2=1.34.0 
  - bioconda::bioconductor-genefilter=1.76.0  
  - bioconda::bioconductor-genomeinfodbdata=1.2.7   
  - bioconda::bioconductor-org.hs.eg.db=3.14.0 
  - bioconda::bioconductor-org.mm.eg.db=3.14.0 
  - bioconda::bioconductor-pathview=1.34.0   
  - bioconda::bioconductor-vsn=3.62.0
  - conda-forge::pandoc=2.17.1.1
  - conda-forge::r-base=4.1.2
  - conda-forge::r-dplyr=1.0.7
  - conda-forge::r-dt=0.20 
  - conda-forge::r-extrafont=0.17
  - conda-forge::r-formattable=0.2.1
  - conda-forge::r-ggplot2=3.3.5
  - conda-forge::r-gplots=3.1.1
  - conda-forge::r-gprofiler2=0.2.1
  - conda-forge::r-kableextra=1.3.4
  - conda-forge::r-knitr=1.37
  - conda-forge::r-optparse=1.7.1
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-plyr=1.8.6
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-rmarkdown=2.11
  - conda-forge::r-svglite=2.1.0
  - conda-forge::r-tidyverse=1.3.1
  - conda-forge::r-yaml=2.2.2
