# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
# use this to find packages: https://anaconda.org/
name: nf-core-rnadeseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-backports=1.1.4
  - hexbin_1.27.2
  - svglite_1.2.1
  - pheatmap_1.0.12
  - gplots_3.0.1.1
  - vsn_3.50.0
  - r-plyr=1.8.4
  - r-ggplot2=3.1.1
  - DESeq2_1.22.2
  - SummarizedExperiment_1.12.0
  - DelayedArray_0.8.0
  - BiocParallel_1.16.6
  - matrixStats_0.54.0
  - Biobase_2.42.0
  - GenomicRanges_1.34.0
  - GenomeInfoDb_1.18.2
  - IRanges_2.16.0
  - RColorBrewer_1.1-2
  - r-bit64=0.9_7
  - splines_3.5.1
  - gtools_3.8.1
  - Formula_1.2-3
  - r-assertthat=0.2.1
  - BiocManager_1.30.4
  - affy_1.60.0
  - latticeExtra_0.6-28
  - r-blob=1.1.1
  - GenomeInfoDbData_1.2.0
  - r-yaml=2.2.0
  - gdtools_0.1.8
  - r-pillar=1.4.0
  - r-rsqlite=2.1.1
  - r-backports=1.1.4
  - r-lattice=0.20_38
  - limma_3.38.3
  - r-glue=1.3.1
  - r-digest=0.6.18
  - bioconductor-xvector=0.22.0
  - checkmate_1.9.3
  - r-colorspace=1.4_1
  - preprocessCore_1.44.0
  - r-htmltools=0.3.6
  - r-matrix=1.2_17
  - r-xml=3.98_1.19
  - r-pkgconfig=2.0.2
  - bioconductor-zlibbioc=1.28.0
  - r-purrr=0.3.2
  - r-xtable=1.8_4
  - r-scales=1.0.0
  - gdata_2.18.0
  - affyio_1.52.0 
  - htmlTable_1.13.1
  - r-tibble=2.1.1
  - bioconductor-annotate=1.60.1
  - r-withr=2.1.2
  - r-nnet=7.3_12
  - r-lazyeval=0.2.2
  - r-survival=2.44_1.10
  - r-magrittr=1.5
  - r-crayon=1.3.4
  - r-memoise=1.1.0
  - r-foreign=0.8_71
  - tools_3.5.1
  - data.table_1.12.2
  - r-stringr=1.4.0
  - r-munsell=0.5.0
  - locfit_1.5-9.1
  - r-cluster=2.0.9
  - bioconductor-annotationdbi=1.44.0
  - compiler_3.5.1
  - r-catools=1.17.1.2
  - r-rlang=0.3.4
  - grid_3.5.1
  - r-rcurl=1.95_4.12
  - r-rstudioapi=0.10
  - r-htmlwidgets=1.3
  - r-labeling=0.3
  - r-bitops=1.0_6
  - r-base64enc=0.1_3
  - r-gtable=0.3.0
  - r-dbi=1.0.0
  - r-r6=2.4.0
  - gridExtra_2.3
  - r-knitr=1.22
  - r-dplyr=0.8.0.1
  - r-bit=1.1_14
  - Hmisc_4.2-0
  - r-kernsmooth=2.23_15
  - r-stringi=1.4.3
  - r-rcpp=1.0.1
  - geneplotter_1.60.0
  - r-rpart=4.1_15
  - acepack_1.4.1
  - r-tidyselect=0.2.5
  - r-xfun=0.6
