# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
# use this to find packages: https://anaconda.org/
name: qbicsoftware-rnadeseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - r-base=3.5.1
  - r::r-hexbin=1.27.2
  - conda-forge::r-svglite=1.2.1
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-gplots=3.0.1.1
  - bioconda::bioconductor-vsn=3.50.0
  - r::r-plyr=1.8.4
  - conda-forge::r-ggplot2=3.1.1
  - conda-forge::r-rcolorbrewer=1.1.2 #1.1_2 in Anaconda
  - bioconda::bioconductor-genefilter=1.64.0
  - bioconda::bioconductor-deseq2=1.22.1 #ResolvePackageNotFound error with version 1.22.2 (as in Rstudio)
  - bioconda::bioconductor-vsn=3.50.0
# additional packages for the RNAseq report
  - conda-forge::r-knitr=1.22
  - conda-forge::r-tidyverse=1.2.1
  - conda-forge::r-dt 0.6
  - r::r-yaml=2.2.0 # chose R channel because conda-forge has only 0.1.7